# This file is the entry point to configure your own services.
parameters:
    images_categories_directory: '%kernel.project_dir%/public/uploads/categories'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\FileUploader:
        arguments:
            $targetDirectory: '%images_categories_directory%'

    App\Service\AiService:
        arguments:
            $apiKey: '%env(OPENROUTER_API_KEY)%'

    App\Controller\Evenement\UserEventController:
        arguments:
            $stripeSecretKey: '%env(STRIPE_SECRET_KEY)%'

    App\Service\EventMailer:
        arguments:
            $fromEmail: '%env(MAILER_FROM_EMAIL)%'
            $fromName:  '%env(MAILER_FROM_NAME)%'
            $appBaseUrl: '%env(APP_BASE_URL)%'
